//! Invocation Handlers
//!
//! This module contains all Tauri command handlers organized by feature.

use super::{
    clipboard_commands, config_commands, hotkey_commands, new_features_commands, pane_commands,
    profile_commands, pty_commands, search_commands, session_commands, tab_commands,
    telemetry_commands, theme_commands,
};

pub fn handlers() -> impl Fn(tauri::Invoke) -> bool + Send + Sync + 'static {
    tauri::generate_handler![
        // Config Commands
        config_commands::get_config,
        config_commands::set_config,
        // PTY Commands
        pty_commands::create_pty_session,
        pty_commands::write_to_pty,
        pty_commands::resize_pty,
        pty_commands::close_pty_session,
        // Tab Commands
        tab_commands::create_tab,
        tab_commands::close_tab,
        tab_commands::switch_tab,
        tab_commands::rename_tab,
        tab_commands::move_tab,
        tab_commands::get_tab,
        tab_commands::get_all_tabs,
        tab_commands::get_tab_layout,
        tab_commands::get_active_tab,
        tab_commands::set_tab_state,
        tab_commands::set_tab_metadata,
        tab_commands::get_tab_metadata,
        tab_commands::get_tab_count,
        tab_commands::has_tabs,
        // Pane Commands
        pane_commands::create_pane,
        pane_commands::close_pane,
        pane_commands::split_pane_horizontal,
        pane_commands::split_pane_vertical,
        pane_commands::resize_pane,
        pane_commands::focus_pane,
        pane_commands::get_pane,
        pane_commands::get_all_panes,
        pane_commands::get_pane_layout,
        pane_commands::get_active_pane,
        pane_commands::get_root_pane,
        pane_commands::get_pane_children,
        pane_commands::is_leaf_pane,
        pane_commands::is_root_pane,
        pane_commands::get_pane_count,
        // Theme Commands
        theme_commands::get_themes,
        theme_commands::get_theme,
        theme_commands::get_active_theme,
        theme_commands::get_active_theme_id,
        theme_commands::apply_theme,
        theme_commands::create_theme,
        theme_commands::update_theme,
        theme_commands::delete_theme,
        theme_commands::import_theme,
        theme_commands::export_theme,
        theme_commands::get_themes_by_variant,
        theme_commands::load_themes_from_disk,
        theme_commands::save_theme_to_disk,
        // Profile Commands
        profile_commands::get_profiles,
        profile_commands::get_profile,
        profile_commands::get_active_profile,
        profile_commands::get_active_profile_id,
        profile_commands::create_profile,
        profile_commands::update_profile,
        profile_commands::delete_profile,
        profile_commands::activate_profile,
        profile_commands::duplicate_profile,
        profile_commands::create_template,
        profile_commands::get_templates,
        profile_commands::get_template,
        profile_commands::apply_template,
        profile_commands::save_profiles_to_disk,
        profile_commands::load_profiles_from_disk,
        profile_commands::search_profiles,
        // Search Commands
        search_commands::search,
        search_commands::update_search,
        search_commands::next_match,
        search_commands::previous_match,
        search_commands::clear_search,
        search_commands::get_search_state,
        search_commands::is_searching,
        search_commands::replace_all,
        search_commands::get_all_search_states,
        // Clipboard Commands
        clipboard_commands::copy,
        clipboard_commands::paste,
        clipboard_commands::paste_from_history,
        clipboard_commands::set_selection,
        clipboard_commands::get_selection,
        clipboard_commands::clear_selection,
        clipboard_commands::has_selection,
        clipboard_commands::get_history,
        clipboard_commands::get_history_items,
        clipboard_commands::search_history,
        clipboard_commands::clear_history,
        clipboard_commands::remove_history_item,
        clipboard_commands::get_clipboard_config,
        clipboard_commands::update_clipboard_config,
        clipboard_commands::get_total_history_size,
        clipboard_commands::is_history_over_limit,
        clipboard_commands::get_recent_items,
        // Hotkey Commands
        hotkey_commands::register_hotkey,
        hotkey_commands::unregister_hotkey,
        hotkey_commands::get_hotkey,
        hotkey_commands::get_all_hotkeys,
        hotkey_commands::get_hotkey_config,
        hotkey_commands::update_hotkey_config,
        hotkey_commands::add_hotkey_context,
        hotkey_commands::remove_hotkey_context,
        hotkey_commands::get_hotkey_context,
        hotkey_commands::get_all_hotkey_contexts,
        hotkey_commands::activate_hotkey_context,
        hotkey_commands::deactivate_hotkey_context,
        hotkey_commands::get_active_hotkey_contexts,
        hotkey_commands::find_hotkey_conflicts,
        hotkey_commands::resolve_hotkey_conflict,
        hotkey_commands::reset_hotkeys_to_defaults,
        hotkey_commands::export_hotkeys,
        hotkey_commands::import_hotkeys,
        // Session Commands
        session_commands::create_session,
        session_commands::update_session,
        session_commands::delete_session,
        session_commands::activate_session,
        session_commands::get_session,
        session_commands::get_all_sessions,
        session_commands::get_active_session,
        session_commands::get_active_session_id,
        session_commands::save_session,
        session_commands::load_session,
        session_commands::restore_last_session,
        session_commands::add_command_to_history,
        session_commands::get_session_history,
        session_commands::search_session_history,
        session_commands::create_session_template,
        session_commands::get_session_templates,
        session_commands::get_session_template,
        session_commands::apply_session_template,
        session_commands::set_session_auto_save,
        session_commands::is_session_auto_save_enabled,
        session_commands::auto_save_active_session,
        session_commands::delete_all_sessions,
        session_commands::search_sessions,
        // Telemetry Commands
        telemetry_commands::log_telemetry_event,
        telemetry_commands::log_telemetry_event_with_level,
        telemetry_commands::log_telemetry_error,
        telemetry_commands::log_telemetry_warning,
        telemetry_commands::log_telemetry_info,
        telemetry_commands::log_telemetry_metric,
        telemetry_commands::log_telemetry_performance_metric,
        telemetry_commands::update_telemetry_performance_metrics,
        telemetry_commands::get_telemetry_performance_metrics,
        telemetry_commands::record_telemetry_startup_time,
        telemetry_commands::record_telemetry_render_time,
        telemetry_commands::record_telemetry_pty_response_time,
        telemetry_commands::record_telemetry_memory_usage,
        telemetry_commands::record_telemetry_cpu_usage,
        telemetry_commands::record_telemetry_fps,
        telemetry_commands::create_telemetry_error_report,
        telemetry_commands::submit_telemetry_error_report,
        telemetry_commands::get_telemetry_events,
        telemetry_commands::get_telemetry_events_by_type,
        telemetry_commands::get_telemetry_errors,
        telemetry_commands::get_telemetry_warnings,
        telemetry_commands::get_telemetry_metrics,
        telemetry_commands::clear_telemetry_events,
        telemetry_commands::clear_telemetry_metrics,
        telemetry_commands::export_telemetry_events,
        telemetry_commands::export_telemetry_metrics,
        telemetry_commands::get_telemetry_config,
        telemetry_commands::update_telemetry_config,
        telemetry_commands::is_telemetry_enabled,
        telemetry_commands::set_telemetry_enabled,
        // Remote Multiplexing Commands
        new_features_commands::create_domain,
        new_features_commands::connect_domain,
        new_features_commands::disconnect_connection,
        new_features_commands::get_domains,
        new_features_commands::get_connections,
        new_features_commands::create_remote_pane,
        new_features_commands::send_remote_input,
        new_features_commands::resize_remote_pane,
        new_features_commands::destroy_remote_pane,
        new_features_commands::persist_remote_session,
        new_features_commands::restore_remote_session,
        new_features_commands::list_persisted_sessions,
        // Plugin Marketplace Commands
        new_features_commands::search_plugins,
        new_features_commands::get_featured_plugins,
        new_features_commands::get_popular_plugins,
        new_features_commands::get_recent_plugins,
        new_features_commands::install_plugin,
        new_features_commands::uninstall_plugin,
        new_features_commands::enable_plugin,
        new_features_commands::disable_plugin,
        new_features_commands::get_installed_plugins,
        new_features_commands::get_plugin_reviews,
        new_features_commands::add_plugin_review,
        // Shell Enhancement Commands
        new_features_commands::add_trigger,
        new_features_commands::remove_trigger,
        new_features_commands::get_triggers,
        new_features_commands::enable_trigger,
        new_features_commands::disable_trigger,
        new_features_commands::evaluate_triggers,
        new_features_commands::add_badge,
        new_features_commands::remove_badge,
        new_features_commands::activate_badge,
        new_features_commands::deactivate_badge,
        new_features_commands::get_active_badges,
        new_features_commands::get_all_badges,
        new_features_commands::add_prompt_template,
        new_features_commands::remove_prompt_template,
        new_features_commands::get_prompt_templates,
        new_features_commands::generate_prompt,
        new_features_commands::generate_default_prompt,
        new_features_commands::set_prompt_variable,
        new_features_commands::get_prompt_variable,
    ]
}
