#[derive(Debug, Clone)]
pub enum Command {
    Save,
    Quit,
    OpenFile,
    NewFile,
    Find,
    Replace,
    GotoLine,
    Format,
    Run,
    Build,
    Test,
    GitCommit,
    GitPush,
    GitPull,
    GitStatus,
    GitBranch,
    GitStash,
    GitCheckout,
    GitMerge,
    GitRebase,
    ToggleLineNumbers,
    ToggleWordWrap,
    ToggleSyntax,
    Theme(String),
    Help,
    SelectWord,
    SelectAllOccurrences,
    SelectLine,
    SelectAllLines,
    ExpandSelection,
    ShrinkSelection,
    ClearSelections,
    TextObjectWord,
    TextObjectLine,
    TextObjectBlock,
    TextObjectFunction,
    TextObjectClass,
    AddSurround,
    ChangeSurround,
    DeleteSurround,
    GoToDefinition,
    GetHover,
    GetCompletions,
    GetDiagnostics,
    ListPlugins,
    LoadPlugin(String),
    UnloadPlugin(String),
    EnablePlugin(String),
    DisablePlugin(String),
    ListThemes,
    SetTheme(String),
}

impl Command {
    pub fn name(&self) -> &str {
        match self {
            Command::Save => "Save",
            Command::Quit => "Quit",
            Command::OpenFile => "Open File",
            Command::NewFile => "New File",
            Command::Find => "Find",
            Command::Replace => "Replace",
            Command::GotoLine => "Goto Line",
            Command::Format => "Format",
            Command::Run => "Run",
            Command::Build => "Build",
            Command::Test => "Test",
            Command::GitCommit => "Git Commit",
            Command::GitPush => "Git Push",
            Command::GitPull => "Git Pull",
            Command::GitStatus => "Git Status",
            Command::GitBranch => "Git Branch",
            Command::GitStash => "Git Stash",
            Command::GitCheckout => "Git Checkout",
            Command::GitMerge => "Git Merge",
            Command::GitRebase => "Git Rebase",
            Command::ToggleLineNumbers => "Toggle Line Numbers",
            Command::ToggleWordWrap => "Toggle Word Wrap",
            Command::ToggleSyntax => "Toggle Syntax",
            Command::Theme(_) => "Theme",
            Command::Help => "Help",
            Command::SelectWord => "Select Word",
            Command::SelectAllOccurrences => "Select All Occurrences",
            Command::SelectLine => "Select Line",
            Command::SelectAllLines => "Select All Lines",
            Command::ExpandSelection => "Expand Selection",
            Command::ShrinkSelection => "Shrink Selection",
            Command::ClearSelections => "Clear Selections",
            Command::TextObjectWord => "Text Object: Word",
            Command::TextObjectLine => "Text Object: Line",
            Command::TextObjectBlock => "Text Object: Block",
            Command::TextObjectFunction => "Text Object: Function",
            Command::TextObjectClass => "Text Object: Class",
            Command::AddSurround => "Add Surround",
            Command::ChangeSurround => "Change Surround",
            Command::DeleteSurround => "Delete Surround",
            Command::GoToDefinition => "Go to Definition",
            Command::GetHover => "Get Hover Info",
            Command::GetCompletions => "Get Completions",
            Command::GetDiagnostics => "Get Diagnostics",
            Command::ListPlugins => "List Plugins",
            Command::LoadPlugin(_) => "Load Plugin",
            Command::UnloadPlugin(_) => "Unload Plugin",
            Command::EnablePlugin(_) => "Enable Plugin",
            Command::DisablePlugin(_) => "Disable Plugin",
            Command::ListThemes => "List Themes",
            Command::SetTheme(_) => "Set Theme",
        }
    }

    pub fn shortcut(&self) -> &str {
        match self {
            Command::Save => "Ctrl+S",
            Command::Quit => "Ctrl+Q",
            Command::OpenFile => "Ctrl+O",
            Command::NewFile => "Ctrl+N",
            Command::Find => "/",
            Command::Replace => ":",
            Command::GotoLine => "gg",
            Command::Format => "Alt+F",
            Command::Run => "F5",
            Command::Build => "F6",
            Command::Test => "F7",
            Command::GitCommit => "gc",
            Command::GitPush => "gp",
            Command::GitPull => "gl",
            Command::GitStatus => "gs",
            Command::GitBranch => "gb",
            Command::GitStash => "gst",
            Command::GitCheckout => "gco",
            Command::GitMerge => "gm",
            Command::GitRebase => "gr",
            Command::ToggleLineNumbers => "nu",
            Command::ToggleWordWrap => "nw",
            Command::ToggleSyntax => "ns",
            Command::Theme(_) => "th",
            Command::Help => "?",
            Command::SelectWord => "sw",
            Command::SelectAllOccurrences => "sa",
            Command::SelectLine => "sl",
            Command::SelectAllLines => "sll",
            Command::ExpandSelection => "se",
            Command::ShrinkSelection => "ss",
            Command::ClearSelections => "sc",
            Command::TextObjectWord => "tow",
            Command::TextObjectLine => "tol",
            Command::TextObjectBlock => "tob",
            Command::TextObjectFunction => "tof",
            Command::TextObjectClass => "toc",
            Command::AddSurround => "as",
            Command::ChangeSurround => "cs",
            Command::DeleteSurround => "ds",
            Command::GoToDefinition => "gd",
            Command::GetHover => "gh",
            Command::GetCompletions => "gc",
            Command::GetDiagnostics => "gd",
            Command::ListPlugins => "lp",
            Command::LoadPlugin(_) => "lpl",
            Command::UnloadPlugin(_) => "upl",
            Command::EnablePlugin(_) => "epl",
            Command::DisablePlugin(_) => "dpl",
            Command::ListThemes => "lt",
            Command::SetTheme(_) => "st",
        }
    }
}
