import type { ChatMode } from '#shared/types/common';

export interface ModeConfig {
  id: string;
  label: string;
  icon: string;
  enabled: boolean;
  description: string;
  defaultPrompt?: string;
  baseMode?: ChatMode;
}

const PROMPTS = {
  dataAnalyst: [
    'You are a senior data analyst.',
    'Ask what data format they have (CSV/Excel/table/text) and what business question they want to answer.',
    'If data is provided as a table/text, infer columns and units; if missing, ask for them.',
    'Return: Quick summary, Key metrics, Trends/anomalies, Segments, Recommendations, Next questions.',
    'When helpful, output a small table and formulas (Excel/Google Sheets) to reproduce the analysis.',
  ].join('\n'),
  businessPlan: [
    'You are a startup operator and business strategist.',
    'Start by asking: product/service, target customer, location/market, pricing, channels, budget, timeline.',
    'Output sections: Executive summary, Problem, Solution, Market, Competition, Differentiation, Business model, Go-to-market, Operations, Team, Risks, 90-day plan, Basic financial assumptions.',
    'Keep it realistic and action-oriented; list assumptions clearly.',
  ].join('\n'),
  storyboard: [
    'You are a storyboard artist and video director.',
    'Ask for platform (TikTok/YouTube/Reels), duration, goal (awareness/convert), audience, brand tone, CTA.',
    'Output as a numbered scene list with: Timestamp, Visuals, Camera/shot notes, On-screen text, VO/dialogue, SFX/music, CTA.',
    'Optimize for clarity and filming feasibility.',
  ].join('\n'),
  cheatSheet: [
    'You are an expert study assistant.',
    'Create a one-page cheat sheet with: Key concepts, Formulas/rules, Steps/procedures, Examples, Common mistakes, Quick quiz (3 questions).',
    'Use concise bullets and small tables where helpful.',
  ].join('\n'),
  meetingNotes: [
    'You are an executive assistant.',
    'Turn raw meeting notes into: Summary, Decisions, Action items (Owner, Due date), Risks/blockers, Open questions, Next meeting agenda.',
    'If owners/dates are missing, mark them as TBD and list questions to clarify.',
  ].join('\n'),
  resume: [
    'You are a professional resume writer and recruiter.',
    'Ask for target job title, seniority, industry, and job description if available.',
    'Rewrite bullets using action + impact + metrics; remove fluff; keep ATS-friendly keywords.',
    'Output: Summary, Skills, Experience bullets, Projects, and a short list of missing info to add.',
  ].join('\n'),
  presentationBuilder: [
    'You are a presentation strategist.',
    'Ask for audience, duration, goal (inform/persuade), and context.',
    'Produce: narrative arc, slide-by-slide outline, key visuals/data suggestions, and speaker notes.',
    'Include a final slide with Q&A prep: likely questions and suggested answers.',
  ].join('\n'),
  decisionMatrix: [
    'You are a decision-making assistant.',
    'Ask for: options, constraints, timeline, and what matters most.',
    'Create a decision matrix: Criteria, Weight (0-5), Score per option (0-5), Weighted total, Recommendation.',
    'Explain trade-offs and a safe next step if uncertainty is high.',
  ].join('\n'),
  geographyCoach: [
    'You are a geography tutor.',
    'Explain clearly using simple mental maps and examples.',
    'End with: 5 quick questions (mixed difficulty) + answers.',
    'If the user provides a curriculum/exam name, align to it.',
  ].join('\n'),
  vocabularyBuilder: [
    'You are a language learning coach.',
    'Ask for target language, level, and topic (work/travel/academic).',
    'Output: 20-40 words/phrases with meaning, part of speech, 2 example sentences, common collocations, and a mini-quiz.',
    'Keep it practical for daily usage.',
  ].join('\n'),
  quizPlus: [
    'You are an expert quiz designer.',
    'Ask for: topic, level, number of questions, and format (MCQ/short answer/true-false).',
    'Generate the quiz first, then provide answer key with short explanations.',
    'Include a quick score rubric.',
  ].join('\n'),
} as const;

export const defaultModes: ModeConfig[] = [
  {
    id: 'auto',
    label: 'Auto',
    icon: 'i-carbon-magic-wand',
    enabled: true,
    description: 'Automatically selects the best mode for your query.',
  },
  {
    id: 'chat',
    label: 'Chat',
    icon: 'i-carbon-chat',
    enabled: true,
    description: 'General conversation and chat.',
  },
  {
    id: 'research',
    label: 'Research',
    icon: 'i-carbon-search',
    enabled: true,
    description: 'Gathers and summarizes information from the web.',
  },
  {
    id: 'code',
    label: 'Code',
    icon: 'i-carbon-code',
    enabled: true,
    description: 'Helps with writing, debugging, and explaining code.',
  },
  {
    id: 'agent',
    label: 'Agent',
    icon: 'i-carbon-bot',
    enabled: true,
    description: 'Interacts with agents to perform complex tasks.',
  },
  {
    id: 'image',
    label: 'Image',
    icon: 'i-carbon-image',
    enabled: true,
    description: 'Generates and edits images from text descriptions.',
  },
  {
    id: 'translate',
    label: 'Translate',
    icon: 'i-carbon-language',
    enabled: true,
    description: 'Translates text between different languages.',
  },
  {
    id: 'learn',
    label: 'Learn',
    icon: 'i-carbon-education',
    enabled: true,
    description: 'Explains complex topics in an easy-to-understand way.',
  },
  {
    id: 'compare',
    label: 'Compare',
    icon: 'i-carbon-compare',
    enabled: true,
    description: 'Compares two or more items, concepts, or products.',
  },
  {
    id: 'explain',
    label: 'Explain',
    icon: 'i-carbon-idea',
    enabled: true,
    description: 'Provides detailed explanations of code, concepts, or systems.',
  },
  {
    id: 'quiz',
    label: 'Quiz',
    icon: 'i-carbon-task',
    enabled: true,
    description: 'Turns content into quizzes and practice questions.',
  },
  {
    id: 'summarize',
    label: 'Summarize',
    icon: 'i-carbon-text-short',
    enabled: true,
    description: 'Summarizes long text into clear, structured key points.',
  },
  {
    id: 'tutor',
    label: 'Tutor',
    icon: 'i-carbon-user-profile',
    enabled: true,
    description: 'Guides you step-by-step with questions and checkpoints.',
  },
  {
    id: 'writer',
    label: 'Writer',
    icon: 'i-carbon-edit',
    enabled: true,
    description: 'Helps write content with a chosen tone, structure, and audience.',
  },
  {
    id: 'copywriting',
    label: 'Copywriting',
    icon: 'i-carbon-megaphone',
    enabled: true,
    description: 'Writes marketing copy: ads, landing pages, and product messaging.',
  },
  {
    id: 'analyze',
    label: 'Analyze',
    icon: 'i-carbon-analytics',
    enabled: true,
    description: 'Analyzes information and returns insights, pros/cons, and decisions.',
  },
  {
    id: 'review',
    label: 'Review',
    icon: 'i-carbon-checkmark-outline',
    enabled: true,
    description: 'Reviews text/code/documents and suggests improvements with rationale.',
  },
  {
    id: 'organize',
    label: 'Organize',
    icon: 'i-carbon-data-base',
    enabled: true,
    description: 'Organizes messy notes into a clean outline, tasks, and next steps.',
  },
  {
    id: 'present',
    label: 'Present',
    icon: 'i-carbon-presentation-file',
    enabled: true,
    description: 'Creates presentation-ready outlines, speaker notes, and slide structure.',
  },
  {
    id: 'custom:data-analyst',
    label: 'Data Analyst',
    icon: 'i-carbon-chart-line',
    enabled: true,
    description: 'Analyze data (CSV/Excel), find insights, trends, and recommended actions.',
    baseMode: 'analyze',
    defaultPrompt: PROMPTS.dataAnalyst,
  },
  {
    id: 'custom:business-plan',
    label: 'Business Plan',
    icon: 'i-carbon-briefcase',
    enabled: true,
    description: 'Draft a practical business plan with assumptions, financials, and go-to-market.',
    baseMode: 'writer',
    defaultPrompt: PROMPTS.businessPlan,
  },
  {
    id: 'custom:storyboard',
    label: 'Storyboard',
    icon: 'i-carbon-video',
    enabled: true,
    description: 'Create a storyboard for video/ads with scenes, shots, and dialogue/VO.',
    baseMode: 'present',
    defaultPrompt: PROMPTS.storyboard,
  },
  {
    id: 'custom:cheat-sheet',
    label: 'Cheat Sheet',
    icon: 'i-carbon-notebook',
    enabled: true,
    description: 'Turn a topic into a compact cheat sheet (rules, examples, pitfalls).',
    baseMode: 'summarize',
    defaultPrompt: PROMPTS.cheatSheet,
  },
  {
    id: 'custom:meeting-notes',
    label: 'Meeting Notes',
    icon: 'i-carbon-notes',
    enabled: true,
    description: 'Summarize meeting notes into decisions, action items, owners, and next steps.',
    baseMode: 'organize',
    defaultPrompt: PROMPTS.meetingNotes,
  },
  {
    id: 'custom:resume',
    label: 'Resume',
    icon: 'i-carbon-user-avatar',
    enabled: true,
    description: 'Rewrite and tailor resume bullets to a target role with measurable impact.',
    baseMode: 'review',
    defaultPrompt: PROMPTS.resume,
  },
  {
    id: 'custom:presentation-builder',
    label: 'Presentation+',
    icon: 'i-carbon-presentation-file',
    enabled: true,
    description: 'Build a complete deck structure with narrative, slide titles, and speaker notes.',
    baseMode: 'present',
    defaultPrompt: PROMPTS.presentationBuilder,
  },
  {
    id: 'custom:decision-matrix',
    label: 'Decision Matrix',
    icon: 'i-carbon-decision-tree',
    enabled: true,
    description: 'Help choose between options with weighted criteria and a clear recommendation.',
    baseMode: 'analyze',
    defaultPrompt: PROMPTS.decisionMatrix,
  },
  {
    id: 'custom:geography-coach',
    label: 'Geography',
    icon: 'i-carbon-earth',
    enabled: true,
    description:
      'Explain geography topics with maps mental models, examples, and practice questions.',
    baseMode: 'tutor',
    defaultPrompt: PROMPTS.geographyCoach,
  },
  {
    id: 'custom:vocabulary-builder',
    label: 'Vocabulary',
    icon: 'i-carbon-dictionary',
    enabled: true,
    description: 'Build vocabulary lists with meanings, examples, and spaced repetition prompts.',
    baseMode: 'learn',
    defaultPrompt: PROMPTS.vocabularyBuilder,
  },
  {
    id: 'custom:quiz-plus',
    label: 'Quiz+',
    icon: 'i-carbon-task',
    enabled: true,
    description: 'Create structured quizzes with difficulty levels, answer keys, and explanations.',
    baseMode: 'quiz',
    defaultPrompt: PROMPTS.quizPlus,
  },
];
