import type { Effect } from "effect";
import type { LinterOptions, FileSystemError, SemanticLinterError } from "./index";
import type { LinterConfig } from "../core/config-loader";

/**
 * Represents a single linting issue found by a plugin.
 */
export interface LintIssue {
  readonly filePath: string;
  readonly message: string;
  readonly ruleName: string;
  readonly line: number;
  readonly column: number;
  readonly severity: "warning" | "error";
  readonly fixable: boolean;
}

/**
 * The report generated by a single linter plugin for a set of files.
 */
export interface PluginLintReport {
  readonly linterName: string;
  readonly issues: readonly LintIssue[];
}

/**
 * The interface that all linter plugins must implement.
 */
export interface LinterPlugin {
  readonly name: string;
  lint(files: readonly string[], options: LinterOptions, config: LinterConfig): Effect.Effect<PluginLintReport, FileSystemError | SemanticLinterError | Error>;
}
