import OpenAI from 'openai';
import { envConfig } from '@/config/env.config';

if (!envConfig.openaiApiKey) {
  throw new Error('OpenAI API key is not configured. Please add it to your .env file.');
}

const openai = new OpenAI({
  apiKey: envConfig.openaiApiKey,
});

export async function generateCommitMessage(diff: string): Promise<string> {
  if (!diff.trim()) {
    return 'style: no changes detected';
  }

  try {
    const response = await openai.chat.completions.create({
      model: 'gpt-3.5-turbo',
      messages: [
        {
          role: 'system',
          content: `You are an expert at writing git commit messages. 
          Write a concise and informative commit message for the following changes. 
          The commit message must follow the conventional commits specification. 
          The output should be only the commit message, without any additional text or explanation.`,
        },
        {
          role: 'user',
          content: diff,
        },
      ],
      temperature: 0.7,
      max_tokens: 100,
    });

    return response.choices[0].message.content?.trim() || 'feat: update files';
  } catch (error) {
    console.error('Error generating commit message:', error);
    return 'feat: update files (autogenerated)';
  }
}
