/* auto-generated by NAPI-RS */
export declare function parse(input: string): string;

export declare function render(input: string): string;

export declare function renderGfm(input: string): string;

export interface RenderOptions {
	sanitize?: boolean;
	syntaxHighlight?: boolean;
	toc?: boolean;
	directives?: boolean;
	gfm?: boolean;
	footnotes?: boolean;
}

export declare function renderWithOptions(
	input: string,
	options?: RenderOptions | undefined | null,
): string;
