import { Effect } from "effect";
import { GitCommandError } from "../errors";
import type { GitRepository } from "../types";
import {
	add,
	addRemote,
	clean,
	checkout,
	cherryPick,
	clone,
	commit,
	deleteTag,
	deleteBranch,
	diffStat,
	fetch,
	getBlame,
	getBranches,
	getCommitDetails,
	getCurrentBranch,
	getConfig,
	getDiff,
	getLog,
	getReflog,
	getRemotes,
	getStashes,
	getStatus,
	init,
	isGitRepository,
	listTags,
	merge,
	pull,
	push,
	rebase,
	renameBranch,
	removeRemote,
	renameRemote,
	reset,
	revert,
	setConfig,
	stash,
	stashApply,
	stashClear,
	stashDrop,
	stashPop,
	tag,
} from "./operations";

const notImplemented = Effect.fail(new GitCommandError({ cause: "Not implemented" }));

export function createGitRepository(path: string): GitRepository {
	return {
		status: () => getStatus(path),
		log: (limit?: number) => getLog(path, limit),
		commit: (message: string, body?: string) => commit(path, message, body),
		isGitRepository: () => isGitRepository(path),
		getCurrentBranch: () => getCurrentBranch(path),
		reflog: (limit?: number) => getReflog(path, limit),
		show: (hash: string) => getCommitDetails(path, hash),
		branch: () => getBranches(path),
		stashList: () => getStashes(path),
		diff: (file?: string, cached?: boolean) => getDiff(path, file ?? "", cached ?? false),
		blame: (file: string) => getBlame(path, file),
		remote: () => getRemotes(path),
		clone: (url: string, destinationPath?: string) => clone(url, destinationPath ?? path),
		add: (files: readonly string[]) => add(path, files),
		reset: (mode: "soft" | "mixed" | "hard", hash?: string) => reset(path, mode, hash),
		checkout: (branch: string, create?: boolean) => checkout(path, branch, create),
		deleteBranch: (name: string, force?: boolean) => deleteBranch(path, name, force),
		pull: (remote?: string, branch?: string, rebase?: boolean) => pull(path, remote, branch, rebase),
		push: (remote?: string, branch?: string, force?: boolean) => push(path, remote, branch, force),
		fetch: (remote?: string, branch?: string) => fetch(path, remote, branch),

		// Phase 1: Core Features
		init: () => init(path),
		stash: (message?: string, includeUntracked?: boolean) => stash(path, message, includeUntracked),
		stashPop: (index?: number) => stashPop(path, index),
		stashApply: (index?: number) => stashApply(path, index),
		stashDrop: (index?: number) => stashDrop(path, index),
		stashClear: () => stashClear(path),
		getConfig: (key: string) => getConfig(path, key),
		setConfig: (key: string, value: string, global?: boolean) => setConfig(path, key, value, global),
		merge: (branch: string, noFf?: boolean) => merge(path, branch, noFf),
		renameBranch: (oldName: string, newName: string) => renameBranch(path, oldName, newName),

		// Phase 2: Advanced Features
		rebase: (branch: string, interactive?: boolean) => rebase(path, branch, interactive),
		cherryPick: (hash: string) => cherryPick(path, hash),
		revert: (hash: string) => revert(path, hash),
		tag: (name: string, message?: string, hash?: string) => tag(path, name, message, hash),
		deleteTag: (name: string) => deleteTag(path, name),
		listTags: () => listTags(path),
		addRemote: (name: string, url: string) => addRemote(path, name, url),
		removeRemote: (name: string) => removeRemote(path, name),
		renameRemote: (oldName: string, newName: string) => renameRemote(path, oldName, newName),
		diffStat: (from?: string, to?: string) => diffStat(path, from, to),
		clean: (force?: boolean, directories?: boolean) => clean(path, force, directories),

		// Methods not implemented yet
		applyPatch: () => notImplemented,
		createPatch: () => notImplemented,
		archive: () => notImplemented,
		submoduleInit: () => notImplemented,
		submoduleUpdate: () => notImplemented,
		worktreeAdd: () => notImplemented,
		worktreeList: () => notImplemented,
		worktreeRemove: () => notImplemented,
		worktreePrune: () => notImplemented,
		bisectStart: () => notImplemented,
		bisectGood: () => notImplemented,
		bisectBad: () => notImplemented,
		bisectReset: () => notImplemented,
		listHooks: () => notImplemented,
		installHook: () => notImplemented,
		removeHook: () => notImplemented,
		getStats: () => notImplemented,
		getContributors: () => notImplemented,
		validateCommitMessage: () => notImplemented,
		getLastCommitMessage: () => notImplemented,
		lfsInstall: () => notImplemented,
		lfsTrack: () => notImplemented,
		lfsUntrack: () => notImplemented,
		lfsLs: () => notImplemented,
		lfsPull: () => notImplemented,
		lfsPush: () => notImplemented,
		submoduleAdd: () => notImplemented,
		submoduleRemove: () => notImplemented,
		submoduleList: () => notImplemented,
		submoduleForeach: () => notImplemented,
		submoduleSync: () => notImplemented,
		getConflicts: () => notImplemented,
		resolveConflict: () => notImplemented,
		abortMerge: () => notImplemented,
		continueMerge: () => notImplemented,
		grep: () => notImplemented,
		searchCommits: () => notImplemented,
		fileHistory: () => notImplemented,
		fileBlame: () => notImplemented,
		amendCommit: () => notImplemented,
		fixupCommit: () => notImplemented,
		squashCommit: () => notImplemented,
		signCommit: () => notImplemented,
		verifyCommit: () => notImplemented,
		listSignedCommits: () => notImplemented,
	};
}
