import { Effect } from "effect";
import type { GitRepository } from "../types";
import { GitCommandError } from "../errors";
import {
    getBlame,
    getBranches,
    getCommitDetails,
    getCurrentBranch,
    getDiff,
    getLog,
    getReflog,
    getRemotes,
    getStashes,
    getStatus,
    isGitRepository,
    commit,
    clone,
    add,
    reset,
    checkout,
    deleteBranch,
    pull,
    push,
    fetch
} from "./operations";

const notImplemented = Effect.fail(new GitCommandError({ cause: "Not implemented" }));

export function createGitRepository(path: string): GitRepository {
    return {
        status: () => getStatus(path),
        log: (limit?: number) => getLog(path, limit),
        commit: (message: string, body?: string) => commit(path, message, body),
        isGitRepository: () => isGitRepository(path),
        getCurrentBranch: () => getCurrentBranch(path),
        reflog: (limit?: number) => getReflog(path, limit),
        show: (hash: string) => getCommitDetails(path, hash),
        branch: () => getBranches(path),
        stashList: () => getStashes(path),
        diff: (file?: string, cached?: boolean) => getDiff(path, file ?? '', cached ?? false),
        blame: (file: string) => getBlame(path, file),
        remote: () => getRemotes(path),
        clone: (url: string, destinationPath?: string) => clone(url, destinationPath ?? path),
        add: (files: readonly string[]) => add(path, files),
        reset: (mode: "soft" | "mixed" | "hard", hash?: string) => reset(path, mode, hash),
        checkout: (branch: string, create?: boolean) => checkout(path, branch, create),
        deleteBranch: (name: string, force?: boolean) => deleteBranch(path, name, force),
        pull: (remote?: string, branch?: string, rebase?: boolean) => pull(path, remote, branch, rebase),
        push: (remote?: string, branch?: string, force?: boolean) => push(path, remote, branch, force),
        fetch: (remote?: string, branch?: string) => fetch(path, remote, branch),

        // Methods not implemented yet
        init: () => notImplemented,
        renameBranch: () => notImplemented,
        merge: () => notImplemented,
        rebase: () => notImplemented,
        cherryPick: () => notImplemented,
        revert: () => notImplemented,
        stash: () => notImplemented,
        stashPop: () => notImplemented,
        stashApply: () => notImplemented,
        stashDrop: () => notImplemented,
        stashClear: () => notImplemented,
        diffStat: () => notImplemented,
        addRemote: () => notImplemented,
        removeRemote: () => notImplemented,
        renameRemote: () => notImplemented,
        tag: () => notImplemented,
        deleteTag: () => notImplemented,
        listTags: () => notImplemented,
        clean: () => notImplemented,
        getConfig: () => notImplemented,
        setConfig: () => notImplemented,
        applyPatch: () => notImplemented,
        createPatch: () => notImplemented,
        archive: () => notImplemented,
        submoduleInit: () => notImplemented,
        submoduleUpdate: () => notImplemented,
        worktreeAdd: () => notImplemented,
        worktreeList: () => notImplemented,
        worktreeRemove: () => notImplemented,
        worktreePrune: () => notImplemented,
        bisectStart: () => notImplemented,
        bisectGood: () => notImplemented,
        bisectBad: () => notImplemented,
        bisectReset: () => notImplemented,
        listHooks: () => notImplemented,
        installHook: () => notImplemented,
        removeHook: () => notImplemented,
        getStats: () => notImplemented,
        getContributors: () => notImplemented,
        validateCommitMessage: () => notImplemented,
        getLastCommitMessage: () => notImplemented,
        lfsInstall: () => notImplemented,
        lfsTrack: () => notImplemented,
        lfsUntrack: () => notImplemented,
        lfsLs: () => notImplemented,
        lfsPull: () => notImplemented,
        lfsPush: () => notImplemented,
        submoduleAdd: () => notImplemented,
        submoduleRemove: () => notImplemented,
        submoduleList: () => notImplemented,
        submoduleForeach: () => notImplemented,
        submoduleSync: () => notImplemented,
        getConflicts: () => notImplemented,
        resolveConflict: () => notImplemented,
        abortMerge: () => notImplemented,
        continueMerge: () => notImplemented,
        grep: () => notImplemented,
        searchCommits: () => notImplemented,
        fileHistory: () => notImplemented,
        fileBlame: () => notImplemented,
        amendCommit: () => notImplemented,
        fixupCommit: () => notImplemented,
        squashCommit: () => notImplemented,
        signCommit: () => notImplemented,
        verifyCommit: () => notImplemented,
        listSignedCommits: () => notImplemented,
    };
}
