import type { DefaultTheme } from "vitepress";

export default function sidebarComposables(): DefaultTheme.SidebarItem[] {
	return [
		{ text: "Overview", link: "/apis/composables/overview" },
		{
			text: "Get Started",
			collapsed: false,
			base: "/apis/composables/get-started",
			items: [{ text: "Usage", link: "/usage" }],
		},
		{
			text: "State Management",
			collapsed: false,
			base: "/apis/composables/composables",
			items: [
				{ text: "useLocalStorage", link: "/useLocalStorage" },
				{ text: "useSessionStorage", link: "/useSessionStorage" },
				{ text: "useAsyncState", link: "/useAsyncState" },
				{ text: "useDark", link: "/useDark" },
				{ text: "useColorMode", link: "/useColorMode" },
			],
		},
		{
			text: "Browser APIs",
			collapsed: false,
			base: "/apis/composables/composables",
			items: [
				{ text: "useClipboard", link: "/useClipboard" },
				{ text: "useFullscreen", link: "/useFullscreen" },
				{ text: "useGeolocation", link: "/useGeolocation" },
				{ text: "useBattery", link: "/useBattery" },
				{ text: "usePermission", link: "/usePermission" },
				{ text: "useVibrate", link: "/useVibrate" },
				{ text: "useWakeLock", link: "/useWakeLock" },
				{ text: "useShare", link: "/useShare" },
				{ text: "useFavicon", link: "/useFavicon" },
			],
		},
		{
			text: "UI/UX",
			collapsed: false,
			base: "/apis/composables/composables",
			items: [
				{ text: "useFocus", link: "/useFocus" },
				{ text: "useDraggable", link: "/useDraggable" },
				{ text: "useDropZone", link: "/useDropZone" },
				{ text: "useSwipe", link: "/useSwipe" },
				{ text: "useIntersectionObserver", link: "/useIntersectionObserver" },
				{ text: "useResizeObserver", link: "/useResizeObserver" },
				{ text: "useElementSize", link: "/useElementSize" },
				{ text: "useCssVar", link: "/useCssVar" },
			],
		},
		{
			text: "Network",
			collapsed: false,
			base: "/apis/composables/composables",
			items: [
				{ text: "useFetch", link: "/useFetch" },
				{ text: "useWebSocket", link: "/useWebSocket" },
				{ text: "useNetwork", link: "/useNetwork" },
				{ text: "useOnline", link: "/useOnline" },
			],
		},
		{
			text: "Device",
			collapsed: false,
			base: "/apis/composables/composables",
			items: [
				{ text: "useMouse", link: "/useMouse" },
				{ text: "useScroll", link: "/useScroll" },
				{ text: "useWindowSize", link: "/useWindowSize" },
				{ text: "useMediaQuery", link: "/useMediaQuery" },
				{ text: "useBreakpoints", link: "/useBreakpoints" },
				{ text: "useDeviceMotion", link: "/useDeviceMotion" },
				{ text: "useDeviceOrientation", link: "/useDeviceOrientation" },
				{ text: "useKeyboard", link: "/useKeyboard" },
			],
		},
		{
			text: "Utilities",
			collapsed: false,
			base: "/apis/composables/composables",
			items: [
				{ text: "useEventListener", link: "/useEventListener" },
				{ text: "useTimeoutFn", link: "/useTimeoutFn" },
				{ text: "useIntervalFn", link: "/useIntervalFn" },
				{ text: "useDebounce", link: "/useDebounce" },
				{ text: "useThrottle", link: "/useThrottle" },
				{ text: "useTitle", link: "/useTitle" },
				{ text: "useDocumentVisibility", link: "/useDocumentVisibility" },
				{ text: "usePageLeave", link: "/usePageLeave" },
				{ text: "useNow", link: "/useNow" },
				{ text: "useDate", link: "/useDate" },
				{ text: "useIdleTimeout", link: "/useIdleTimeout" },
				{ text: "usePreferredLanguages", link: "/usePreferredLanguages" },
				{ text: "useImage", link: "/useImage" },
				{ text: "useFileDialog", link: "/useFileDialog" },
				{ text: "useInfiniteScroll", link: "/useInfiniteScroll" },
			],
		},
	];
}
