use super::command_types::{Command, CommandCategory};
use crate::types::Shortcut;

pub fn default_commands() -> Vec<Command> {
    vec![
        Command::new(
            "open_file",
            "Open File",
            "Open a file in the editor",
            CommandCategory::File,
            Some("Ctrl+O"),
        ),
        Command::new(
            "save_file",
            "Save File",
            "Save the current file",
            CommandCategory::File,
            Some("Ctrl+S"),
        ),
        Command::new(
            "new_file",
            "New File",
            "Create a new file",
            CommandCategory::File,
            Some("Ctrl+N"),
        ),
        Command::new(
            "close_file",
            "Close File",
            "Close the current file",
            CommandCategory::File,
            Some("Ctrl+W"),
        ),
        Command::new(
            "search",
            "Search",
            "Search in the current file",
            CommandCategory::Search,
            Some("Ctrl+F"),
        ),
        Command::new(
            "search_files",
            "Search Files",
            "Search across all files",
            CommandCategory::Search,
            Some("Ctrl+Shift+F"),
        ),
        Command::new(
            "git_status",
            "Git Status",
            "Show git status",
            CommandCategory::Git,
            None::<Shortcut>,
        ),
        Command::new(
            "git_commit",
            "Git Commit",
            "Commit changes",
            CommandCategory::Git,
            None::<Shortcut>,
        ),
        Command::new(
            "git_push",
            "Git Push",
            "Push changes to remote",
            CommandCategory::Git,
            None::<Shortcut>,
        ),
        Command::new(
            "run_tests",
            "Run Tests",
            "Run all tests",
            CommandCategory::Run,
            None::<Shortcut>,
        ),
        Command::new(
            "run_build",
            "Run Build",
            "Build the project",
            CommandCategory::Run,
            None::<Shortcut>,
        ),
        Command::new(
            "toggle_file_explorer",
            "Toggle File Explorer",
            "Show/hide file explorer",
            CommandCategory::View,
            Some("Ctrl+1"),
        ),
        Command::new(
            "toggle_chat",
            "Toggle Chat",
            "Show/hide chat panel",
            CommandCategory::View,
            Some("Ctrl+2"),
        ),
        Command::new(
            "toggle_output",
            "Toggle Output",
            "Show/hide output panel",
            CommandCategory::View,
            Some("Ctrl+3"),
        ),
        Command::new(
            "help",
            "Help",
            "Show help and key bindings",
            CommandCategory::Help,
            Some("?"),
        ),
        Command::new(
            "ai_explain_code",
            "AI: Explain Code",
            "Ask AI to explain the selected code",
            CommandCategory::AI,
            None::<Shortcut>,
        ),
        Command::new(
            "ai_generate_code",
            "AI: Generate Code",
            "Generate code from natural language description",
            CommandCategory::AI,
            None::<Shortcut>,
        ),
        Command::new(
            "ai_refactor",
            "AI: Refactor Code",
            "Refactor code with AI suggestions",
            CommandCategory::AI,
            None::<Shortcut>,
        ),
        Command::new(
            "ai_generate_tests",
            "AI: Generate Tests",
            "Generate unit tests for the code",
            CommandCategory::AI,
            None::<Shortcut>,
        ),
        Command::new(
            "ai_find_bugs",
            "AI: Find Bugs",
            "Analyze code for potential bugs",
            CommandCategory::AI,
            None::<Shortcut>,
        ),
        Command::new(
            "ai_document",
            "AI: Generate Documentation",
            "Generate documentation for the code",
            CommandCategory::AI,
            None::<Shortcut>,
        ),
        Command::new(
            "ai_optimize",
            "AI: Optimize Code",
            "Optimize code for performance",
            CommandCategory::AI,
            None::<Shortcut>,
        ),
        Command::new(
            "ai_clear_cache",
            "AI: Clear Cache",
            "Clear AI response cache",
            CommandCategory::AI,
            None::<Shortcut>,
        ),
    ]
}
