import { glob } from "glob";
import path from "path";
import fs from "fs/promises";

const API_DIR = path.resolve(process.cwd(), "src", "api");
const OUTPUT_FILE = path.resolve(process.cwd(), "src", "generated", "routes.ts");

async function generateRoutes() {
  console.log("🔥 Generating routes...");

  const routeFiles = await glob(`${API_DIR}/**/*.ts`);
  const imports: string[] = [];
  const routeDefs: string[] = [];

  for (const [index, file] of routeFiles.entries()) {
    const relativePath = path.relative(API_DIR, file);
    const importName = `route${index}`;

    // 1. Create import statement
    const importPath = path.relative(path.dirname(OUTPUT_FILE), file).replace(/\\/g, "/").replace(".ts", "");
    imports.push(`import * as ${importName} from "${importPath}";`);

    // 2. Create route definition
    let urlPath = `/${relativePath.replace(/\\/g, "/").replace(/\.ts$/, "")}`;
    const httpMethodMatch = urlPath.match(/\.(get|post|put|delete|patch)$/);
    const httpMethod = httpMethodMatch ? httpMethodMatch[1].toUpperCase() : "GET";
    urlPath = urlPath.replace(/\.(get|post|put|delete|patch)$/, "");
    urlPath = urlPath.replace(/index$/, "").replace(/\/$/, "") || "/";

    routeDefs.push(`  {
    method: "${httpMethod}" as const,
    path: "${urlPath}",
    ...${importName},
  }`);
  }

  const content = `// This file is auto-generated by tools/build-routes.ts
import type { RouteDefinition } from "../types";

${imports.join("\n")}

export const generatedRoutes: RouteDefinition[] = [
${routeDefs.join(",\n")},
];
`;

  await fs.mkdir(path.dirname(OUTPUT_FILE), { recursive: true });
  await fs.writeFile(OUTPUT_FILE, content);

  console.log(`✅ Routes generated at ${path.relative(process.cwd(), OUTPUT_FILE)}`);
}

generateRoutes().catch((err) => {
  console.error("Error generating routes:", err);
  process.exit(1);
});
