import { Language } from "../types";

export const SUPPORTED_LANGUAGES = Object.freeze([
	"javascript",
	"typescript",
	"python",
	"java",
	"csharp",
	"go",
	"rust",
	"cpp",
	"c",
	"php",
	"ruby",
	"swift",
	"kotlin",
	"dart",
	"scala",
	"haskell",
	"elixir",
	"erlang",
	"clojure",
	"fsharp",
	"r",
	"julia",
	"lua",
	"perl",
	"bash",
	"powershell",
	"sql",
	"html",
	"css",
	"json",
	"yaml",
	"xml",
	"markdown",
] as const satisfies readonly Language[]);

export const LANGUAGE_ALIASES = Object.freeze({
	js: "javascript",
	ts: "typescript",
	py: "python",
	java: "java",
	csharp: "csharp",
	cs: "csharp",
	go: "go",
	rs: "rust",
	cpp: "cpp",
	c: "c",
	php: "php",
	rb: "ruby",
	swift: "swift",
	kt: "kotlin",
	dart: "dart",
	scala: "scala",
	hs: "haskell",
	ex: "elixir",
	erl: "erlang",
	clj: "clojure",
	fs: "fsharp",
	r: "r",
	jl: "julia",
	lua: "lua",
	pl: "perl",
	sh: "bash",
	ps1: "powershell",
	sql: "sql",
	html: "html",
	css: "css",
	json: "json",
	yaml: "yaml",
	yml: "yaml",
	xml: "xml",
	md: "markdown",
	markdown: "markdown",
} as const);

export const LANGUAGE_EXTENSIONS = Object.freeze({
	javascript: [".js", ".mjs", ".cjs"],
	typescript: [".ts", ".mts", ".cts"],
	python: [".py"],
	java: [".java"],
	csharp: [".cs"],
	go: [".go"],
	rust: [".rs"],
	cpp: [".cpp", ".cc", ".cxx", ".hpp", ".h"],
	c: [".c", ".h"],
	php: [".php"],
	ruby: [".rb"],
	swift: [".swift"],
	kotlin: [".kt", ".kts"],
	dart: [".dart"],
	scala: [".scala"],
	haskell: [".hs"],
	elixir: [".ex", ".exs"],
	erlang: [".erl", ".hrl"],
	clojure: [".clj", ".cljs", ".cljc"],
	fsharp: [".fs", ".fsi", ".fsx"],
	r: [".r", ".R"],
	julia: [".jl"],
	lua: [".lua"],
	perl: [".pl", ".pm"],
	bash: [".sh", ".bash"],
	powershell: [".ps1", ".psm1"],
	sql: [".sql"],
	html: [".html", ".htm"],
	css: [".css"],
	json: [".json"],
	yaml: [".yaml", ".yml"],
	xml: [".xml"],
	markdown: [".md", ".markdown"],
} as const);
