/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NapiIndex {
	constructor();
	addDocuments(docs: Array<JsDocument>): void;
	buildIndex(): void;
	searchIds(query: string): Array<number>;
	search(query: string): Array<JsDocument>;
}

export interface JsDocument {
	fields: FxHashMap<string, string>;
}
