// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require("node:fs");
let nativeBinding = null;
const loadErrors = [];

const isMusl = () => {
	let musl = false;
	if (process.platform === "linux") {
		musl = isMuslFromFilesystem();
		if (musl === null) {
			musl = isMuslFromReport();
		}
		if (musl === null) {
			musl = isMuslFromChildProcess();
		}
	}
	return musl;
};

const isFileMusl = (f) => f.includes("libc.musl-") || f.includes("ld-musl-");

const isMuslFromFilesystem = () => {
	try {
		return readFileSync("/usr/bin/ldd", "utf-8").includes("musl");
	} catch {
		return null;
	}
};

const isMuslFromReport = () => {
	let report = null;
	if (typeof process.report?.getReport === "function") {
		process.report.excludeNetwork = true;
		report = process.report.getReport();
	}
	if (!report) {
		return null;
	}
	if (report.header && report.header.glibcVersionRuntime) {
		return false;
	}
	if (Array.isArray(report.sharedObjects)) {
		if (report.sharedObjects.some(isFileMusl)) {
			return true;
		}
	}
	return false;
};

const isMuslFromChildProcess = () => {
	try {
		return require("child_process")
			.execSync("ldd --version", { encoding: "utf8" })
			.includes("musl");
	} catch (e) {
		// If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
		return false;
	}
};

function requireNative() {
	if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
		try {
			return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
		} catch (err) {
			loadErrors.push(err);
		}
	} else if (process.platform === "android") {
		if (process.arch === "arm64") {
			try {
				return require("./search.android-arm64.node");
			} catch (e) {
				loadErrors.push(e);
			}
			try {
				return require("@wdocs/search-android-arm64");
			} catch (e) {
				loadErrors.push(e);
			}
		} else if (process.arch === "arm") {
			try {
				return require("./search.android-arm-eabi.node");
			} catch (e) {
				loadErrors.push(e);
			}
			try {
				return require("@wdocs/search-android-arm-eabi");
			} catch (e) {
				loadErrors.push(e);
			}
		} else {
			loadErrors.push(
				new Error(`Unsupported architecture on Android ${process.arch}`),
			);
		}
	} else if (process.platform === "win32") {
		if (process.arch === "x64") {
			if (
				process.config?.variables?.shlib_suffix === "dll.a" ||
				process.config?.variables?.node_target_type === "shared_library"
			) {
				try {
					return require("./search.win32-x64-gnu.node");
				} catch (e) {
					loadErrors.push(e);
				}
				try {
					return require("@wdocs/search-win32-x64-gnu");
				} catch (e) {
					loadErrors.push(e);
				}
			} else {
				try {
					return require("./search.win32-x64-msvc.node");
				} catch (e) {
					loadErrors.push(e);
				}
				try {
					return require("@wdocs/search-win32-x64-msvc");
				} catch (e) {
					loadErrors.push(e);
				}
			}
		} else if (process.arch === "ia32") {
			try {
				return require("./search.win32-ia32-msvc.node");
			} catch (e) {
				loadErrors.push(e);
			}
			try {
				return require("@wdocs/search-win32-ia32-msvc");
			} catch (e) {
				loadErrors.push(e);
			}
		} else if (process.arch === "arm64") {
			try {
				return require("./search.win32-arm64-msvc.node");
			} catch (e) {
				loadErrors.push(e);
			}
			try {
				return require("@wdocs/search-win32-arm64-msvc");
			} catch (e) {
				loadErrors.push(e);
			}
		} else {
			loadErrors.push(
				new Error(`Unsupported architecture on Windows: ${process.arch}`),
			);
		}
	} else if (process.platform === "darwin") {
		try {
			return require("./search.darwin-universal.node");
		} catch (e) {
			loadErrors.push(e);
		}
		try {
			return require("@wdocs/search-darwin-universal");
		} catch (e) {
			loadErrors.push(e);
		}
		if (process.arch === "x64") {
			try {
				return require("./search.darwin-x64.node");
			} catch (e) {
				loadErrors.push(e);
			}
			try {
				return require("@wdocs/search-darwin-x64");
			} catch (e) {
				loadErrors.push(e);
			}
		} else if (process.arch === "arm64") {
			try {
				return require("./search.darwin-arm64.node");
			} catch (e) {
				loadErrors.push(e);
			}
			try {
				return require("@wdocs/search-darwin-arm64");
			} catch (e) {
				loadErrors.push(e);
			}
		} else {
			loadErrors.push(
				new Error(`Unsupported architecture on macOS: ${process.arch}`),
			);
		}
	} else if (process.platform === "freebsd") {
		if (process.arch === "x64") {
			try {
				return require("./search.freebsd-x64.node");
			} catch (e) {
				loadErrors.push(e);
			}
			try {
				return require("@wdocs/search-freebsd-x64");
			} catch (e) {
				loadErrors.push(e);
			}
		} else if (process.arch === "arm64") {
			try {
				return require("./search.freebsd-arm64.node");
			} catch (e) {
				loadErrors.push(e);
			}
			try {
				return require("@wdocs/search-freebsd-arm64");
			} catch (e) {
				loadErrors.push(e);
			}
		} else {
			loadErrors.push(
				new Error(`Unsupported architecture on FreeBSD: ${process.arch}`),
			);
		}
	} else if (process.platform === "linux") {
		if (process.arch === "x64") {
			if (isMusl()) {
				try {
					return require("./search.linux-x64-musl.node");
				} catch (e) {
					loadErrors.push(e);
				}
				try {
					return require("@wdocs/search-linux-x64-musl");
				} catch (e) {
					loadErrors.push(e);
				}
			} else {
				try {
					return require("./search.linux-x64-gnu.node");
				} catch (e) {
					loadErrors.push(e);
				}
				try {
					return require("@wdocs/search-linux-x64-gnu");
				} catch (e) {
					loadErrors.push(e);
				}
			}
		} else if (process.arch === "arm64") {
			if (isMusl()) {
				try {
					return require("./search.linux-arm64-musl.node");
				} catch (e) {
					loadErrors.push(e);
				}
				try {
					return require("@wdocs/search-linux-arm64-musl");
				} catch (e) {
					loadErrors.push(e);
				}
			} else {
				try {
					return require("./search.linux-arm64-gnu.node");
				} catch (e) {
					loadErrors.push(e);
				}
				try {
					return require("@wdocs/search-linux-arm64-gnu");
				} catch (e) {
					loadErrors.push(e);
				}
			}
		} else if (process.arch === "arm") {
			if (isMusl()) {
				try {
					return require("./search.linux-arm-musleabihf.node");
				} catch (e) {
					loadErrors.push(e);
				}
				try {
					return require("@wdocs/search-linux-arm-musleabihf");
				} catch (e) {
					loadErrors.push(e);
				}
			} else {
				try {
					return require("./search.linux-arm-gnueabihf.node");
				} catch (e) {
					loadErrors.push(e);
				}
				try {
					return require("@wdocs/search-linux-arm-gnueabihf");
				} catch (e) {
					loadErrors.push(e);
				}
			}
		} else if (process.arch === "loong64") {
			if (isMusl()) {
				try {
					return require("./search.linux-loong64-musl.node");
				} catch (e) {
					loadErrors.push(e);
				}
				try {
					return require("@wdocs/search-linux-loong64-musl");
				} catch (e) {
					loadErrors.push(e);
				}
			} else {
				try {
					return require("./search.linux-loong64-gnu.node");
				} catch (e) {
					loadErrors.push(e);
				}
				try {
					return require("@wdocs/search-linux-loong64-gnu");
				} catch (e) {
					loadErrors.push(e);
				}
			}
		} else if (process.arch === "riscv64") {
			if (isMusl()) {
				try {
					return require("./search.linux-riscv64-musl.node");
				} catch (e) {
					loadErrors.push(e);
				}
				try {
					return require("@wdocs/search-linux-riscv64-musl");
				} catch (e) {
					loadErrors.push(e);
				}
			} else {
				try {
					return require("./search.linux-riscv64-gnu.node");
				} catch (e) {
					loadErrors.push(e);
				}
				try {
					return require("@wdocs/search-linux-riscv64-gnu");
				} catch (e) {
					loadErrors.push(e);
				}
			}
		} else if (process.arch === "ppc64") {
			try {
				return require("./search.linux-ppc64-gnu.node");
			} catch (e) {
				loadErrors.push(e);
			}
			try {
				return require("@wdocs/search-linux-ppc64-gnu");
			} catch (e) {
				loadErrors.push(e);
			}
		} else if (process.arch === "s390x") {
			try {
				return require("./search.linux-s390x-gnu.node");
			} catch (e) {
				loadErrors.push(e);
			}
			try {
				return require("@wdocs/search-linux-s390x-gnu");
			} catch (e) {
				loadErrors.push(e);
			}
		} else {
			loadErrors.push(
				new Error(`Unsupported architecture on Linux: ${process.arch}`),
			);
		}
	} else if (process.platform === "openharmony") {
		if (process.arch === "arm64") {
			try {
				return require("./search.openharmony-arm64.node");
			} catch (e) {
				loadErrors.push(e);
			}
			try {
				return require("@wdocs/search-openharmony-arm64");
			} catch (e) {
				loadErrors.push(e);
			}
		} else if (process.arch === "x64") {
			try {
				return require("./search.openharmony-x64.node");
			} catch (e) {
				loadErrors.push(e);
			}
			try {
				return require("@wdocs/search-openharmony-x64");
			} catch (e) {
				loadErrors.push(e);
			}
		} else if (process.arch === "arm") {
			try {
				return require("./search.openharmony-arm.node");
			} catch (e) {
				loadErrors.push(e);
			}
			try {
				return require("@wdocs/search-openharmony-arm");
			} catch (e) {
				loadErrors.push(e);
			}
		} else {
			loadErrors.push(
				new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`),
			);
		}
	} else {
		loadErrors.push(
			new Error(
				`Unsupported OS: ${process.platform}, architecture: ${process.arch}`,
			),
		);
	}
}

nativeBinding = requireNative();

if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
	let wasiBinding = null;
	let wasiBindingError = null;
	try {
		wasiBinding = require("./search.wasi.cjs");
		nativeBinding = wasiBinding;
	} catch (err) {
		if (process.env.NAPI_RS_FORCE_WASI) {
			wasiBindingError = err;
		}
	}
	if (!nativeBinding) {
		try {
			wasiBinding = require("@wdocs/search-wasm32-wasi");
			nativeBinding = wasiBinding;
		} catch (err) {
			if (process.env.NAPI_RS_FORCE_WASI) {
				wasiBindingError.cause = err;
				loadErrors.push(err);
			}
		}
	}
	if (process.env.NAPI_RS_FORCE_WASI === "error" && !wasiBinding) {
		const error = new Error(
			"WASI binding not found and NAPI_RS_FORCE_WASI is set to error",
		);
		error.cause = wasiBindingError;
		throw error;
	}
}

if (!nativeBinding) {
	if (loadErrors.length > 0) {
		throw new Error(
			`Cannot find native binding. ` +
				`npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
				"Please try `npm i` again after removing both package-lock.json and node_modules directory.",
			{
				cause: loadErrors.reduce((err, cur) => {
					cur.cause = err;
					return cur;
				}),
			},
		);
	}
	throw new Error(`Failed to load native binding`);
}

module.exports = nativeBinding;
module.exports.NapiIndex = nativeBinding.NapiIndex;
